import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "@/components/common/Navber";
import Footer from "@/components/common/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AnyTech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-[100vh]">
         
          <div className="flex-grow">
            <Navber />
          </div>

          <div className="">   
            {children}
          </div>

          <div className="flex-shrink-0">
            <Footer />
          </div>

        </div>
      </body>
    </html>
  );
}
